# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Neptune_config = debug
  SandBox_config = debug
  Test_config = debug

else ifeq ($(config),release)
  Neptune_config = release
  SandBox_config = release
  Test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Neptune SandBox Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Neptune:
ifneq (,$(Neptune_config))
	@echo "==== Building Neptune ($(Neptune_config)) ===="
	@${MAKE} --no-print-directory -C Neptune -f Makefile config=$(Neptune_config)
endif

SandBox: Neptune
ifneq (,$(SandBox_config))
	@echo "==== Building SandBox ($(SandBox_config)) ===="
	@${MAKE} --no-print-directory -C SandBox -f Makefile config=$(SandBox_config)
endif

Test: Neptune
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C Test -f Makefile config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C Neptune -f Makefile clean
	@${MAKE} --no-print-directory -C SandBox -f Makefile clean
	@${MAKE} --no-print-directory -C Test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Neptune"
	@echo "   SandBox"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"