# @file build-deploy.yml
# @brief This file is the configuration for the build-deploy in GitHub.
# @author Spices.

# configuration name
name: build-deploy

# workflow trigger
on:
  
  # On Pushed
  push:
    branches: [ "main" ]
  
  # On Pull Request
  pull_request:
    branches: [ "main" ]

# workflow jobs
jobs:
  
  # Environment Prepare
  environment-prepare:
    
    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Build Steps
    steps:

    # Checkout recursive
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set Emscripten
    - name: Set up Emscripten
      id: setup-emsdk
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: 'latest'

    # Cache emsdk
    - name: Cache Emscripten
      uses: actions/cache@v3
      with:
        path: |
          ~/.emsdk
          ~/.emscripten_cache
        key: ${{ runner.os }}-emsdk-${{ steps.setup-emsdk.outputs.emsdk-version }}

  # Build Wasm Debug Files
  build-wasm-debug:

    # Need environment-prepare first
    needs: environment-prepare

    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Build Steps
    steps:

    # Build Solution with Debug Configuration
    - name: Build Debug
      shell: bash
      working-directory: ./Scripts/BuildEntry/
      run: bash bash ./gmake_build_debug_wasm.sh

    # Find build file
    - name: Find build outputs
      run: |
        echo "Searching for build outputs..."
        find . -name "*.wasm" -o -name "*.js"
        echo "WASM_DEBUG_OUTPUT_PATH=$(find . -name "*.wasm" | head -n 1 | xargs dirname)" >> $GITHUB_ENV

    # Upload wasm and js
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-debug-artifacts
        path: ./bin/Debug-emscripten-wasm64/SandBox/
        retention-days: 3

  # Build Wasm Release Files
  build-wasm-release:

    # Need environment-prepare first
    needs: environment-prepare

    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Build Steps
    steps:

    # Build Solution with Release Configuration
    - name: Build Release
      shell: bash
      working-directory: ./Scripts/BuildEntry/
      run: bash ./gmake_build_release_wasm.sh

    # Find build file
    - name: Find build outputs
      run: |
        echo "Searching for build outputs..."
        find . -name "*.wasm" -o -name "*.js"
        echo "WASM_RELEASE_OUTPUT_PATH=$(find . -name "*.wasm" | head -n 1 | xargs dirname)" >> $GITHUB_ENV

    # Upload wasm and js
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-release-artifacts
        path: ./bin/Release-emscripten-wasm64/SandBox/
        retention-days: 3

  # Deploy Job
  deploy:

    # Need build-wasm first
    needs:
      - build-wasm-debug
      - build-wasm-release

    # build must be success
    if: needs.build-wasm-debug.result == 'success' && needs.build-wasm-release.result == 'success'

    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Deploy Steps
    steps:
      - uses: actions/checkout@v4

      # check lock file is exist
      - name: Check lockfile
        id: check_lockfile
        working-directory: ./Nepnep
        run: |
          if [ -f package-lock.json ]; then
            echo "lockfile_exists=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile_exists=false" >> $GITHUB_OUTPUT
          fi

      # Initial npm install
      - name: Initial npm install
        working-directory: ./Nepnep
        run: npm install
        if: steps.check_lockfile.outputs.lockfile_exists == 'false'

      # Download debug wasm and js
      - name: Download debug artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-debug-artifacts
          path: ./Nepnep/public/wasm/Debug/
            
      # Download release wasm and js
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-release-artifacts
          path: ./Nepnep/public/wasm/Release/

      # Set Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './Nepnep/package-lock.json'

      # Npm Install
      - name: Npm ci Install
        working-directory: ./Nepnep
        run: npm ci
        if: steps.check_lockfile.outputs.lockfile_exists == 'true'

      # Npm Prisma Generate
      - name: Generate Prisma Client
        working-directory: ./Nepnep
        run: npm run prisma:generate

      # Npm Build
      - name: Npm Build
        working-directory: ./Nepnep
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        id: deploy-to-vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: './Nepnep'

      # Show deploy detail
      - name: Show deployment URL
        run: |
          echo "Deployment URL: ${{ steps.deploy-to-vercel.outputs.project-url }}"
