# @file build-deploy.yml
# @brief This file is the configuration for the build-deploy in GitHub.
# @author Spices.

# configuration name
name: build-deploy

# workflow trigger
on:
  
  # On Pushed
  push:
    branches: [ "main" ]
  
  # On Pull Request
  pull_request:
    branches: [ "main" ]

# workflow jobs
jobs:
  
  # Build Job
  build-wasm:
    
    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Build Steps
    steps:

    # Checkout recursive
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set Emscripten
    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: 'latest'

    # Cache emsdk
    - name: Cache Emscripten
      uses: actions/cache@v3
      with:
        path: |
          ~/.emsdk
          ~/.emscripten_cache
        key: ${{ runner.os }}-emsdk-${{ steps.setup-emsdk.outputs.emsdk-version }}

    # Build Solution with Release Configuration
    - name: Build Release
      shell: bash
      working-directory: ./Scripts/BuildEntry/
      run: bash ./gmake_build_release_wasm.sh

    # Find build file
    - name: Find build outputs
      run: |
        echo "Searching for build outputs..."
        find . -name "*.wasm" -o -name "*.js"
        echo "WASM_OUTPUT_PATH=$(find . -name "*.wasm" | head -n 1 | xargs dirname)" >> $GITHUB_ENV

    # Upload wasm and js
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-artifacts
        path: ./Nepnep/static/wasm/
        retention-days: 3

  # Deploy Job
  deploy:

    # Need build-wasm first
    needs: build-wasm

    # build must be success
    if: needs.build-wasm.result == 'success'

    # Platform: Ubuntu
    runs-on: ubuntu-latest

    # Deploy Steps
    steps:
      - uses: actions/checkout@v4

      # Generate lockfile
      - name: Generate lockfile
        working-directory: ./Nepnep
        run: npm install
        if: !exists('./Nepnep/package-lock.json')

      # Download wasm and js
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-artifacts
          path: ./Nepnep/static/wasm/

      # Set Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './Nepnep/package-lock.json'
        if: exists('./Nepnep/package-lock.json')

      # Npm Install
      - name: Npm Install
        working-directory: ./Nepnep
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Npm Build
      - name: Npm Build
        working-directory: ./Nepnep
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}